---
name: Build and push container
on:
  push:
    branches:
      - main
      - prod
      - staging
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker build and push
    steps:
      - uses: actions/checkout@v4
      - uses: metacpan/metacpan-actions/docker-build-push@master
        id: build-push
        with:
          docker_hub_username: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_TOKEN }}
          ghcr_username: ${{ github.repository_owner }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
      - uses: metacpan/metacpan-actions/docker-build-push@master
        id: build-push
        with:
          docker_hub_username: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_TOKEN }}
          ghcr_username: ${{ github.repository_owner }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
          slim: true
