---
name: Build deployment container
on:
  push:
    branches:
      - prod
      - staging
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-22.04
    name: Docker push deployment
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: metacpan/metacpan-base:$GITHUB_SHA
          platforms: linux/amd64,linux/arm64
      - name: Build and push slim
        uses: docker/build-push-action@v5
        with:
          push: true
          build-arg:
            - SLIM_BUILD=1
          tags: metacpan/metacpan-base:$GITHUB_SHA-slim
          platforms: linux/amd64,linux/arm64
