---
name: Test container build
on: [pull_request, workflow_dispatch]
jobs:
  docker:
    runs-on: ubuntu-22.04
    name: Docker Test
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build . -t metacpan/metacpan-base:test
